Remove undefined reference to _namespace_map
_namespace_map is internal to ElementTree but it isn't needed by mbxml
anyway (hence the error hasn't been noticed yet) so just remove it.